#version: "3.9"
services:
  de_mysql:
    image: mysql:8.0
    container_name: de_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - env
    networks:
      - de_network
    
  de_psql:
    image: postgres:15
    container_name: de_psql
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - env
    networks:
      - de_network

  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - minio_data:/data
    env_file:
      - env
    networks:
      - de_network

  mc:
    image: minio/mc
    container_name: mc
    hostname: mc
    env_file:
      - env
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 minio minio123); do
         echo '...waiting...' && sleep 1;
       done;
       /usr/bin/mc mb minio/warehouse;
       /usr/bin/mc policy set public minio/warehouse;
       exit 0;"
    depends_on:
      - minio
    networks:
      - de_network

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.5.0
    container_name: dbt
    env_file:
      - env
    networks:
      - de_network
    volumes:
      - dbt_data:/dbt
    working_dir: /dbt
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/dbt seed); do
        echo '...waiting...' && sleep 1;
      done;
      /usr/bin/dbt run;
      /usr/bin/dbt test;
      /usr/bin/dbt docs generate;
      /usr/bin/dbt docs serve --port 8080;
      exit 0;"

volumes:
  mysql_data:
    name: de_mysql_data
  postgresql_data:
    name: de_postgresql_data
  minio_data:
    name: de_minio_data
  dbt_data:
    name: de_dbt_data

networks:
  de_network:
    driver: bridge
    name: de_network
    external: true